<?php

/**
 * Configuration bootstrapper for WordPress
 *
 * DO NOT EDIT THIS FILE.
 *
 * Edit the config files found in the `config/` directory instead.
 * This file is required in the root directory so WordPress can find it.
 * WordPress is hardcoded to look in its own directory or one directory up
 * for `wp-config.php`.
 */

use Dotenv\Dotenv;
use Roots\WPConfig\Config;

use function Env\env;

/** Absolute path to the public document root directory. */
define( 'Jazz\\APP_PUBLIC_PATH', __DIR__ );

/** Absolute path to the project root directory. */
define( 'Jazz\\APP_BASE_PATH', dirname( __DIR__ ) );

/** Absolute path to the project configuration directory. */
define( 'Jazz\\APP_CONFIG_PATH', Jazz\APP_BASE_PATH . '/config' );

/** Absolute path to the Composer vendor directory. */
define( 'Jazz\\APP_VENDOR_PATH', Jazz\APP_BASE_PATH . '/vendor' );

/** Name of to the WordPress core directory. */
define( 'Jazz\\WP_BASE_DIRNAME', 'wordpress' );

/** Absolute path to the WordPress core directory. Without a trailing slash. */
define( 'Jazz\\WP_BASE_PATH', Jazz\APP_PUBLIC_PATH . '/' . Jazz\WP_BASE_DIRNAME );

/** Absolute path to the WordPress directory. Contains a trailing slash. */
if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', WP_BASE_PATH . '/' );
}

/** Loads the WordPress Plugin API early to allow Composer dependencies to use hooks. */
require_once Jazz\WP_BASE_PATH . '/wp-includes/plugin.php';

/** Registers the Composer autoloader. */
require_once Jazz\APP_VENDOR_PATH . '/autoload.php';

/**
 * Fires once the Composer autoloader has loaded.
 *
 * @fires action:jazz/bootstrap/autoloader_loaded
 */
do_action( 'jazz/bootstrap/autoloader_loaded' );

/**
 * Use Dotenv to set required environment variables and load .env file in root
 */
$dotenv = Dotenv::createUnsafeImmutable( Jazz\APP_BASE_PATH );
if ( file_exists( Jazz\APP_BASE_PATH . '/.env' ) ) {
	$dotenv->load();
	$dotenv->required( [
		'WP_HOME',
		'WP_SITEURL',
	] );

	if ( ! env( 'DATABASE_URL' ) ) {
		$dotenv->required( [
			'DB_NAME',
			'DB_USER',
			'DB_PASSWORD',
		] );
	}
}

/**
 * Set up our global environment constant and load its config first.
 *
 * Default: production
 */
define( 'WP_ENVIRONMENT_TYPE', ( env( 'WP_ENVIRONMENT_TYPE' ) ?? 'production' ) );

/** The `WP_ENV` constant is required by certain plugins from Roots for Bedrock. */
define( 'WP_ENV', ( env( 'WP_ENV' ) ?? WP_ENVIRONMENT_TYPE ) );

/**
 * Fires once the environment variables are loaded and
 * the environment type is determined.
 *
 * @fires action:jazz/bootstrap/environment_loaded
 */
do_action( 'jazz/bootstrap/environment_loaded' );

/**
 * Set up the project's config, then WordPress' config, then the environment.
 */
require_once Jazz\APP_CONFIG_PATH . '/wordpress.php';
require_once Jazz\APP_CONFIG_PATH . '/application.php';

$env_conf = Jazz\APP_CONFIG_PATH . '/environments/' . WP_ENVIRONMENT_TYPE . '.php';
if ( file_exists( $env_conf ) ) {
	require_once $env_conf;
}

/**
 * Defines all constants and throw an exception if we are attempting to redefine a constant.
 */
Config::apply();

/**
 * Fires once the WordPress and application configuration files
 * are loaded.
 *
 * @fires action:jazz/bootstrap/config_loaded
 */
do_action( 'jazz/bootstrap/config_loaded' );

/** Sets up WordPress vars and included files. */
require_once Jazz\WP_BASE_PATH . '/wp-settings.php';
