<?php

/**
 * Configuration bootstrapper for WordPress
 *
 * Do not edit this file. Edit the config files found in the config/ directory instead.
 * This file is required in the root directory so WordPress can find it.
 * WordPress is hardcoded to look in its own directory or one directory up for wp-config.php.
 */

/** Absolute path to the public document root directory. */
define( 'Jazz\APP_PUBLIC_PATH', __DIR__ );

/** @var string Absolute path to the project root directory. */
define( 'Jazz\APP_BASE_PATH', dirname( __DIR__ ) );

/** @var string Absolute path to the project configuration directory. */
define( 'Jazz\APP_CONFIG_PATH', \Jazz\APP_BASE_PATH . '/config' );

/** @var string Absolute path to the Composer vendor directory. */
define( 'Jazz\APP_VENDOR_PATH', \Jazz\APP_BASE_PATH . '/vendor' );

/** Absolute path to the WordPress directory. Contains a trailing slash. */
if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/wordpress' . '/' );
}

/** Registers the Composer Autoloader */
require_once Jazz\APP_VENDOR_PATH . '/autoload.php';

/** Sets up the Jazz framework and imports WordPress configuration files */
require_once Jazz\APP_CONFIG_PATH . '/bootstrap.php';

/** Sets up WordPress vars and included files */
require_once ABSPATH . 'wp-settings.php';
