<?php

/**
 * Configuration Bootstrapper
 *
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
 */

use Dotenv\Dotenv;
use Roots\WPConfig\Config;

use function Env\env;

use const Jazz\APP_BASE_PATH;

/**
 * Use Dotenv to set required environment variables and load .env file in root
 */
$dotenv = Dotenv::createUnsafeImmutable( APP_BASE_PATH );
if ( file_exists( APP_BASE_PATH . '/.env' ) ) {
    $dotenv->load();
    $dotenv->required( [
        'WP_HOME',
        'WP_SITEURL',
    ] );

    if ( ! env( 'DATABASE_URL' ) ) {
        $dotenv->required( [
            'DB_NAME',
            'DB_USER',
            'DB_PASSWORD',
        ] );
    }
}

/**
 * Set up our global environment constant and load its config first.
 * The `WP_ENV` constant is required by certain plugins from Roots
 * for Bedrock.
 * Default: production
 */
define( 'WP_ENVIRONMENT_TYPE', ( env( 'WP_ENVIRONMENT_TYPE' ) ?? 'production' ) );
define( 'WP_ENV', ( env( 'WP_ENV' ) ?? WP_ENVIRONMENT_TYPE ) );

/**
 * Set up the project's config, then WordPress' config, then the environment.
 */
require_once __DIR__ . '/application.php';
require_once __DIR__ . '/wordpress.php';

$env_conf = __DIR__ . '/environments/' . WP_ENVIRONMENT_TYPE . '.php';
if ( file_exists( $env_conf ) ) {
    require_once $env_conf;
}

/**
 * Defines all constants and throw an exception if we are attempting to redefine a constant.
 */
Config::apply();
